/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/Floating_Anim_bake2.gltf
*/

import React, { useRef, useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { useProgress } from '@react-three/drei'

export default function Clone(props) {
  useEffect(() => {
    actions.Floating_Anim_0.play()
  })

  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/Floating_Anim_bake2.gltf')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null} scale={2}>
      <group>
        <skinnedMesh
          name='GEN01_CLONE_Highress__1_'
          geometry={nodes.GEN01_CLONE_Highress__1_.geometry}
          material={materials.Gen01_Clone_02_Material_O}
          skeleton={nodes.GEN01_CLONE_Highress__1_.skeleton}>
          <primitive object={nodes.Hips} />
        </skinnedMesh>
      </group>
    </group>
  )
}

useGLTF.preload('/Floating_Anim_bake2.gltf')
