/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/scene.gltf
Author: DM-913 (https://sketchfab.com/SuperKapoo913)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cursed-undead-soldier-rig-b2e39de76b834d978adee5716aec814d
Title: Cursed Undead Soldier Rig
*/

import React, { useRef, useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/scene.gltf')
  const { actions } = useAnimations(animations, group)

  useEffect(() => {
    actions.Slash.play()
  })

  return (
    <group ref={group} {...props} dispose={null}>
      <group name='Sketchfab_Scene' scale='.01'>
        <group name='Sketchfab_model' rotation={[-Math.PI / 2, 0, 0]}>
          <group name='root'>
            <group name='GLTF_SceneRootNode' rotation={[Math.PI / 2, 0, 0]}>
              <group name='Circle002_2' position={[0, 397.16, 1.15]} rotation={[Math.PI / 2, 0, 0]} scale={6.75}>
                <mesh name='Object_4' geometry={nodes.Object_4.geometry} material={materials.material_0} />
              </group>
              <group name='Circle003_3' position={[0, 397.16, 1.15]} rotation={[-Math.PI / 2, 0, 0]} scale={6.75}>
                <mesh name='Object_6' geometry={nodes.Object_6.geometry} material={materials.material_0} />
              </group>
              <group
                name='Circle006_6'
                position={[0, 397.16, 1.15]}
                rotation={[-Math.PI, 0, 0]}
                scale={[-12.27, 12.27, 12.27]}>
                <mesh name='Object_8' geometry={nodes.Object_8.geometry} material={materials.material_0} />
              </group>
              <group name='Circle007_7' position={[0, 397.16, 1.15]} rotation={[-Math.PI / 2, 0, 0]} scale={6.75}>
                <mesh name='Object_10' geometry={nodes.Object_10.geometry} material={materials.material_0} />
              </group>
              <group name='Circle008_8' position={[0, 397.16, 1.15]} rotation={[-Math.PI / 2, 0, 0]} scale={6.75}>
                <mesh name='Object_12' geometry={nodes.Object_12.geometry} material={materials.material_0} />
              </group>
              <group name='Text_9' position={[0, 397.16, 1.15]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={8.07}>
                <mesh name='Object_14' geometry={nodes.Object_14.geometry} material={materials.material_0} />
              </group>
              <group
                name='Text001_10'
                position={[0, 397.16, 1.15]}
                rotation={[-Math.PI / 2, -Math.PI / 2, 0]}
                scale={8.07}>
                <mesh name='Object_16' geometry={nodes.Object_16.geometry} material={materials.material_0} />
              </group>
              <group name='Undead_Armature_97' position={[0, -2.86, 1.15]} scale={2.55}>
                <group name='GLTF_created_0'>
                  <primitive object={nodes.GLTF_created_0_rootJoint} />
                  <group name='Undead_Gear_Mesh_95' />
                  <group name='Undead_Mesh_96' />
                  <skinnedMesh
                    name='Object_21'
                    geometry={nodes.Object_21.geometry}
                    material={materials.Undead_Gear}
                    skeleton={nodes.Object_21.skeleton}
                  />
                  <skinnedMesh
                    name='Object_23'
                    geometry={nodes.Object_23.geometry}
                    material={materials.Undead_Material}
                    skeleton={nodes.Object_23.skeleton}
                  />
                  <skinnedMesh
                    name='Object_24'
                    geometry={nodes.Object_24.geometry}
                    material={materials.material}
                    skeleton={nodes.Object_24.skeleton}
                  />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
